### ISSUE TITLE
Queue API endpoints

### ISSUE THREAD

**Issue by Julien00859** [EPHEC-TI/WebGames#12]
The current API for queues is not usable by the manager and furthermore is ugly.

None URL follow the Naming Convention for REST API described here: http://www.restapitutorial.com/lessons/restfulresourcenaming.html

Exemple:

    DELETE /queue/remove HTTP/1.1
    content-type: plaintext; charset=utf-8

    bomberman

Instead of 

    DELETE /queues/bomberman HTTP/1.1

Another problem is the HTTP Status of `/queue/states` and `/queue/actives` when the database request returns an empty result. The current status is `404 - Not found` this is not correct as the client could predict the non-existence of any queue or any active queue. The status should be `200 - Ok` with an empty JSON array in the body or `204 - No content` without any thing in the body.

I don't have the time nor the motivation to learn Sequelize + Express in order to correct the API myself in a pull request.

The following are required by the Queue Manager:
* List of actives games. Endpoint suggested `/queues/actives`
* Whole object for a specific game. Endpoint suggested `/queues/<game>`
* Number of players needed for a specific game. Endpoint suggested `/queues/<game>/<attribute>`

**Comment by Mathieu-R** [comment]
As far as I've understood there are 4 endpoints:
- Get status of all games (+ number of players needed).
- Get status of one specifice game.
- Get informations about all the actives games.
- Remove a specific game.

It seems that it has changed but the endpoint for the actives games, right ?

**Comment by Julien00859** [comment]
I wasn't clear about what I needed in the past weeks. The current architecture works as follow:

1) When the manager start it caches the list of actives games (`/queue/actives`)
2) When player join a queue, the manager check for the queue length, if it as enough players to start a game, the game is started. (`/queues/<queue joined by the player>/numbers_players_needed`)
3) When a game is starting, the manager needs to know everything about it (docker image, port list, maybe some others things, this part is not writted yet) (`/queues/<queue>`)

The old endpoints are obsolete in the current architecture and can be fully deleted
