### ISSUE TITLE
cross dependence

### ISSUE THREAD

**Issue by Julien00859** [EPHEC-TI/WebGames#18]
The WebAPI needs the Manager to be running on startup but the Manager also needs the WebAPI to be running at startup.

But to be running, the Manager also needs Nginx to be running which starts when the WebAPI is ready. It would be a lot of work to make the WebAPI connection at runtime in both nginx and the manager. So can you work on a solution to create the connection with the manager at runtime ?

**Comment by Julien00859** [comment]
nginx_1     | 2017/07/27 12:13:17 Waiting for: http://webapi:5000/check
	manager_1   | 2017/07/27 12:13:17 Waiting for: http://api.webgames.ephec-ti.be/check
	nginx_1     | 2017/07/27 12:13:18 Problem with request: Get http://webapi:5000/check: dial tcp 172.19.0.4:5000: getsockopt: connection refused. Sleeping 1s
	manager_1   | 2017/07/27 12:13:18 Problem with request: Get http://api.webgames.ephec-ti.be/check: dial tcp 172.19.0.5:80: getsockopt: connection refused. Sleeping 1s
	webapi_1    | $ npm run build && node server.js
	webapi_1    | 
	webapi_1    | > webgames-api@1.0.0 build /usr/src/app
	webapi_1    | > rollup -c admin/rollup.config.production.js
	webapi_1    | 
	webapi_1    | (1): admin/scripts/app.js
	webapi_1    | (2): admin/scripts/login.js
	webapi_1    | (3): admin/scripts/toast.js
	webapi_1    | Warning: 'idb-keyval' is imported by admin/scripts/login.js, but could not be resolved – treating it as an external dependency
	webapi_1    | https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
	webapi_1    | 
	webapi_1    | (4): admin/scripts/admin.js
	webapi_1    | Warning: 'idb-keyval' is imported by admin/scripts/admin.js, but could not be resolved – treating it as an external dependency
	webapi_1    | https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
	webapi_1    | 
	webapi_1    | ┌────────────────────────────────────────────────┐
	webapi_1    | │                                                │
	webapi_1    | │   Destination: ./admin/static/bundle.js        │
	webapi_1    | │   Bundle size: 3.6 KB, Gzipped size: 1.11 KB   │
	webapi_1    | │                                                │
	webapi_1    | └────────────────────────────────────────────────┘
	webapi_1    | Warning: connect-redis expects a number for the "db" option
	webapi_1    | [WebGames] Admin page running on port 5000
	webapi_1    | events.js:182
	webapi_1    |       throw er; // Unhandled 'error' event
	webapi_1    |       ^
	webapi_1    | 
	webapi_1    | Error: connect ECONNREFUSED 172.19.0.6
	webapi_1    |     at Object.exports._errnoException (util.js:1024:11)
	webapi_1    |     at exports._exceptionWithHostPort (util.js:1047:20)
	webapi_1    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
	webapi_1    | error Command failed with exit code 1.
	webapi_1    | 2017/07/27 12:13:20 Command exited with error: exit status 1
	webgames_webapi_1 exited with code 1
	nginx_1     | 2017/07/27 12:13:20 Problem with request: Get http://webapi:5000/check: dial tcp 172.19.0.4:5000: getsockopt: connection refused. Sleeping 1s
	manager_1   | 2017/07/27 12:13:20 Problem with request: Get http://api.webgames.ephec-ti.be/check: dial tcp 172.19.0.5:80: getsockopt: connection refused. Sleeping 1s

**Comment by Mathieu-R** [comment]
What do you mean by `create the connection with the manager at runtime` ?

If the manager is not alive, I am not able to create the connection. 
Do you want me to do a kind of `try and retry until connection is done` ?

**Comment by Julien00859** [comment]
smth like that, or open the socket (if it does not exists) when the api needs to send smth.
