### ISSUE TITLE
resetPasswordForm should be a middleware not a simple function

### ISSUE THREAD

**Issue by Mathieu-R** [EPHEC-TI/WebGames#2]
For now, `resetPasswordForm`is a function that check id and token and authorize the password modification in consequence by a redirection.

I think that's a terrible design and not securised at all as the route to reset the password is open to everyone.

`resetPasswordForm` should be a middleware that allow the user or not to hit the route to effectively reset the password.

```js
function resetPasswordMiddleware(req, res, next) {
  const {id, token} = req.query;
  User.findById(id).then(user => {
    if (!user) {
      res.status(404).json({error: 'utilisateur non trouvé... Hack ?'});
      return;
    }

    if (user.u_reset_expiration < Date.now()) {
      res.status(400).json({error: 'Token de réinitialisation de mot de passe expiré'});
      return;
    }

    if (token !== user.u_reset_password_token) {
      res.status(400).json({error: 'Token de réinitialisation de mot de passe invalide'});
      return;
    }

    next()
  }).catch(error => {
    res.status(500).json({error});
  });
}

router.put('/api/account/reset', validateReset, resetPasswordMiddleware, resetPassword);
```

**Comment by Mathieu-R** [comment]
I think it should be both (function in `user-controller.js` and middleware).

**Comment by izanagi1995** [comment]
No need for a middleware, you can do it in a function and if the conditions are not met, just send an error page. That's not less secure

**Comment by Mathieu-R** [comment]
But with that, the `/api/account/reset` endpoint is accessible to everyone.
Furthermore, as the reset password page is open, there's no time limit to change the password anymore which does not make sense.

**Comment by izanagi1995** [comment]
That's not a problem! The token make the security for you. For the time limit, put a date limit in the token.

**Comment by Mathieu-R** [comment]
I see how I should implement the stuff. Thanks !
